### ISSUE TITLE
Unable to start web editor

### ISSUE THREAD

**Issue by ddwwcc** [KenT2/pipresents-gtk#9]
Hi Ken,
Sorry to add to you're problems, when you're trying to sort out what's happening with the moving target that is Bookworm. Hopefully it's a simple one.

I've just installed gtk on a Raspberry Pi 5, fully up to date with Bookworm. I't's not a clean install, as there is other stuff installed, as well. I can run mediashow without problem. But, when I try and start the web editor, I just see 'HTTP request sent; waiting for response.' on the command line, but no web page opens. I have the Chromium and Firefox browsers that are installed as standard.

When I quit, on the command line, the following is shown:

Found pp_web.cfg in  /home/pi/pipresents/pp_config/pp_web.cfg
remi.server      INFO     Started httpserver http://127.0.0.1:8082/

Exiting via interrupt: 2

Traceback (most recent call last):
  File "/home/pi/pipresents/remi/server.py", line 818, in start
    import android
ModuleNotFoundError: No module named 'android'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/pipresents/pp_web_editor.py", line 1604, in <module>
    start(PPWebEditor,address=ip, port=network.editor_port,username=network.editor_username,password=network.editor_password,
  File "/home/pi/pipresents/remi/server.py", line 900, in start
    s = Server(main_gui_class, start=True, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/pipresents/remi/server.py", line 791, in __init__
    self.start()
  File "/home/pi/pipresents/remi/server.py", line 825, in start
    webbrowser.open(self._base_address)
  File "/usr/lib/python3.11/webbrowser.py", line 87, in open
    if browser.open(url, new, autoraise):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/webbrowser.py", line 182, in open
    return not p.wait()
               ^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1262, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1997, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1955, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Hope this helps to trace the problem, and if you want any further testing, just ask.

Thanks for you super software.

Cheers

**Comment by lxne** [comment]
There is something about this in the manual.
I had the same issue but it worked after doing this…

> This will open the Chrome browser and display the editor gui. However there seems
> to be a bug in the March 24 issue of Bookworm which causes this command to hang.
> I solved it by making Firefox the default browser and then making Chrome the default
> browser again.

**Comment by ddwwcc** [comment]
> There is something about this in the manual. I had the same issue but it worked after doing this…
> 
> > This will open the Chrome browser and display the editor gui. However there seems
> > to be a bug in the March 24 issue of Bookworm which causes this command to hang.
> > I solved it by making Firefox the default browser and then making Chrome the default
> > browser again.

Thanks for that. I hadn't spotted that in the manual. I shall try that.

**Comment by ddwwcc** [comment]
Yes, this worked: Instructions:

In Raspberry Pi Configuration, System tab. Browser: Select Firefox. Save.

Reopen Raspberry Pi Configuration, System tab. Browser: Select Chromium. Save.

**Comment by KenT2** [comment]
This does not occur in Trixie as of Feb 26
Chromium does now bring up some new error messages. It seems OK to ignore them
